baseURL = "https://alibaba.github.io/Dragonfly/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Dragonfly Documentation"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/alibaba/Dragonfly/edit/master/docs/"
  description = "DragonFly Documentation"
  author = "Team Dragonfly"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "dragonfly"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "DragonFly Documentation"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> View on Github"
identifier = "ds"
url = "https://d7y.io"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-map-signs'></i> Roadmap"
url = "roadmap"
weight = 2
