services:
  - docker
sudo: false
language: java
jdk:
  - oraclejdk8
script:
  - export LOG_HOME=/tmp/supernode && ./build/build.sh supernode
  # - (cd ./build/client && ./configure && make unit-test) && export LOG_HOME=/tmp/supernode && ./build/build.sh

# after_success:
#   - bash <(curl -s https://codecov.io/bash) || echo "Failed to report code coverage!"

cache:
  directories:
    - .autoconf
    - $HOME/.m2
