# This file is the template of dfget configuration file.
# You can configure your dfget by change the parameter according your requirement.

# Nodes specify supernodes.
nodes:
  　- 127.0.0.1
  　- 10.10.10.1

# LocalLimit rate limit about a single download task, format: G(B)/g/M(B)/m/K(B)/k/B
# pure number will also be parsed as Byte.
localLimit: 20M

# Minimal rate about a single download task, format: G(B)/g/M(B)/m/K(B)/k/B
# pure number will also be parsed as Byte.
minRate: 512

# TotalLimit rate limit about the whole host, format: G(B)/g/M(B)/m/K(B)/k/B
# pure number will also be parsed as Byte.
totalLimit: 40M

# ClientQueueSize is the size of client queue
# which controls the number of pieces that can be processed simultaneously.
# It is only useful when the Pattern equals "source".
# The default value is 6.
clientQueueSize: 6
